/**
 * 서버 ErrorCode enum과 동기화된 에러 코드 상수
 * @see payper-server/.../global/response/ErrorCode.java
 */
export const ErrorCode = {
  // GENERAL
  BAD_REQUEST: "GEN-001",
  NOT_FOUND: "GEN-003",
  CONFLICT: "GEN-004",
  INTERNAL_SERVER_ERROR: "GEN-005",

  // JWT
  JWT_ERROR: "JWT_001",
  JWT_EXPIRED: "JWT_002",
  JWT_REISSUE_ERROR: "JWT_003",
  JWT_REISSUE_EXPIRED: "JWT_004",
  JWT_REISSUE_OLD: "JWT_005",
  REISSUE_ERROR: "JWT_006",

  // SECURITY / AUTH
  UNAUTHENTICATED: "SEC-001",
  UNAUTHORIZED: "SEC-002",
  USER_DUPLICATE: "SEC-003",
  USER_NOT_FOUND_AUTH: "SEC-004",
  USER_INACTIVE: "SEC-005",

  // OAUTH
  OAUTH_RESOURCE_ERROR: "OAUTH-001",

  // USER
  USER_NOT_FOUND: "USER-001",
  NOT_AN_ADMIN: "USER-002",

  // POST
  POST_NOT_FOUND: "POST-001",
  NOT_POST_AUTHOR: "POST-002",

  // COMMENT
  COMMENT_NOT_FOUND: "COMMENT-001",
  NOT_COMMENT_AUTHOR: "COMMENT-002",
  POST_NOT_COMMENTABLE: "COMMENT-003",
  INVALID_PARENT_COMMENT: "COMMENT-004",

  // MERCHANT
  MERCHANT_NOT_FOUND: "MERCHANT-001",
  MERCHANT_ALREADY_EXISTS: "MERCHANT-002",

  // CATEGORY
  CATEGORY_NOT_FOUND: "CATEGORY-001",
  CATEGORY_ALREADY_EXISTS: "CATEGORY-002",
  CATEGORY_DEPTH_EXCEEDED: "CATEGORY-003",
  CATEGORY_CANNOT_BE_SELF_PARENT: "CATEGORY-004",
  PARENT_CATEGORY_CANNOT_HAVE_PARENT: "CATEGORY-005",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
