name: Build & Test

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Expo health check
        run: npx expo doctor

      - name: Expo bundle check
        run: npx expo export --platform web

      - name: Run tests
        run: npm test
